substitutions:
  device_name: remeha
  friendly_name: Remeha Tzerra Ace Matic

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  #build_path: "../build/${device_name}"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

#external_components:
#- source: github://hencou/esphome_gvret
#  components: [canbus_gvret]
#  refresh: 0s
  
# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssidC
  password: !secret wifi_passwordC
  min_auth_mode: WPA2
  enable_btm: True
  enable_rrm: True

time:
  - platform: homeassistant
#    on_time:
#      - seconds: /1
#        then:
#          - canbus.send:
#              canbus_id: can1
#              data: [0x40, 0x1d, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00]
#          - canbus.send:
#              canbus_id: can1
#             data: [0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

sensor:
- platform: uptime
  name: Uptime
  id: ${device_name}_uptime
  filters:
    - throttle: 300s
- platform: wifi_signal
  name: WiFi signal
  id: ${device_name}_wifi_signal
  filters:
    - delta: 0.01
    - throttle: 300s

- platform: template
  name: Flow temperatuur
  id: ${device_name}_flow_temperature
  icon: "mdi:thermometer"
  unit_of_measurement: "°C"
  device_class: "temperature"
- platform: template
  name: Setpoint
  id: ${device_name}_setpoint
  icon: "mdi:thermometer"
  unit_of_measurement: "°C"
  device_class: "temperature"
- platform: template
  name: AM027 Buiten temperatuur
  id: ${device_name}_am027_outside_temp
  icon: "mdi:thermometer"
  unit_of_measurement: "°C"
  device_class: "temperature"
- platform: template
  name: Buiten temperatuur 3min avg
  id: ${device_name}_outside_temp_3m_avg
  icon: "mdi:thermometer"
  unit_of_measurement: "°C"
  device_class: "temperature"
- platform: template
  name: Buiten temperatuur 2h avg
  id: ${device_name}_outside_temp_2h_avg
  icon: "mdi:thermometer"
  unit_of_measurement: "°C"
  device_class: "temperature"
- platform: template
  name: AM024 Relative Power
  id: ${device_name}_am024_rel_power
- platform: template
  name: Relative Power2
  id: ${device_name}_rel_power2
- platform: template
  name: AM012 Status
  id: ${device_name}_am012_status
- platform: template
  name: AM014 Substatus
  id: ${device_name}_am014_substatus
  
text_sensor:
- platform: version
  id: ${device_name}_esphome_versie
  name: ESPHome versie
- platform: wifi_info
  ip_address:
    name: IP address
    id: ${device_name}_ipaddress
  ssid:
    name: SSID
    id: ${device_name}_ssid
  bssid:
    name: BSSID
    id: ${device_name}_bssid
    
- platform: template
  name: AM012 Status tekst
  id: ${device_name}_am012_statustext
- platform: template
  name: AM014 Substatus tekst
  id: ${device_name}_am014_substatustext

button:
- platform: factory_reset
  name: Factory reset
  id: ${device_name}_factory_restart
  entity_category: config
- platform: restart
  name: Restart
  id: ${device_name}_restart
  entity_category: config
- platform: safe_mode
  entity_category: config
  name: Safemode
  id: ${device_name}_safemode

canbus:
- platform: esp32_can
  id: can1
  tx_pin: GPIO5
  rx_pin: GPIO35
  can_id: 0x241
  bit_rate: 1000kbps
  # increase queue sizes for CANOpen block transfer (up to 128 frames can be sent in burst)
  tx_queue_len: 128
  rx_queue_len: 128
  on_frame:
  - can_id: 0x282
    then:
    - lambda: |-
        if(x.size() > 0) {
          uint8_t A;
          uint8_t B;

          //Byte0 = AM024 Relative Power
          uint8_t rel_power = x[0];
          id(${device_name}_am024_rel_power).publish_state(rel_power);
          
          //Byte 2+3 = Flow temperature
          A = x[2];
          B = x[3];
          float flow_temp = (((uint16_t)A << 8) + B) / 100.00;
          id(${device_name}_flow_temperature).publish_state(flow_temp);
        }

  - can_id: 0x381
    then:
    - lambda: |-
        if(x.size() > 0) {
          uint8_t A;
          uint8_t B;

          //Byte 0+1 = AM027 Outside temperature //converts to int16 can be negative
          A = x[0];
          B = x[1];
          float out_temp = (int16_t(((uint16_t)B << 8) + A) / 100.00);
          id(${device_name}_am027_outside_temp).publish_state(out_temp);

          //Byte 2+3 = Outside temperature 3min avg //converts to int16 can be negative
          A = x[2];
          B = x[3];
          float out_temp_3min_avg = (int16_t(((uint16_t)B << 8) + A) / 100.00);
          id(${device_name}_outside_temp_3m_avg).publish_state(out_temp_3min_avg);

          //Byte 4+5 = Outside temperature 2h avg //converts to int16 can be negative
          A = x[4];
          B = x[5];
          float out_temp_2h_avg = (int16_t(((uint16_t)B << 8) + A) / 100.00);
          id(${device_name}_outside_temp_2h_avg).publish_state(out_temp_2h_avg);
        }

  - can_id: 0x382
    then:
    - lambda: |-
        if(x.size() > 0) {
          uint8_t A;
          uint8_t B;

          //Byte 2+3 = Setpoint
          A = x[2];
          B = x[3];
          float setpoint = (((uint16_t)A << 8) + B) / 100.00;
          id(${device_name}_setpoint).publish_state(setpoint);
        }
        
  - can_id: 0x481
    then:
    - lambda: |-
        if(x.size() > 0) {
          uint8_t A;
          uint8_t B;

          //Byte 0 = AM012_status
          A = x[0];
          float am012_status = A;
          id(${device_name}_am012_status).publish_state(am012_status);

          //Byte 1 = AM014_substatus
          B = x[1];
          float am014_substatus = B;
          id(${device_name}_am014_substatus).publish_state(am014_substatus);

          //Byte0 = AM012 Status
          uint8_t status = x[0];
          std::string am012_statustext;
          switch(status) {
            case 0:
              am012_statustext="Standby";
              break;
            case 1:
              am012_statustext="Heat request";
              break;
            case 2:
              am012_statustext="Burner ignition";
              break;
            case 3:
              am012_statustext="Heating mode";
              break;
            case 4:
              am012_statustext="DHW mode";
              break;
            case 5:
              am012_statustext="Burner off";
              break;
            case 6:
              am012_statustext="Pump active";
              break;
            case 8:
              am012_statustext="Burner shut down";
              break;
            case 9:
              am012_statustext="Temporary fault";
              break;
            case 10:
              am012_statustext="Permanent fault";
              break;
            case 11:
              am012_statustext="Test heat min";
              break;
            case 12:
              am012_statustext="Test heat max";
              break;
            case 13:
              am012_statustext="Test DWH max";
              break;
            case 15:
              am012_statustext="Manual heat";
              break;
            case 16:
              am012_statustext="Frost protection";
              break;
            case 17:
              am012_statustext="Bleed air";
              break;
            case 19:
              am012_statustext="Reset";
              break;
            case 20:
              am012_statustext="Automatic filling";
              break;
            case 22:
              am012_statustext="Forced calibration";
              break;
            case 200:
              am012_statustext="Service mode";
              break;
            default:
              am012_statustext="Unknown";
          }
          id(${device_name}_am012_statustext).publish_state(am012_statustext.c_str());

          //Byte1 = AM014 Substatus
          uint8_t substatus = x[1];
          std::string am014_substatustext;
          switch(substatus) {
            case 0:
              am014_substatustext="Standby";
              break;
            case 1:
              am014_substatustext="Waiting ignition";
              break;
            case 4:
              am014_substatustext="Waiting for temperature";
              break;
            case 13:
              am014_substatustext="Pre-ventilation";
              break;
            case 15:
              am014_substatustext="Ignition signal sent";
              break;
            case 17:
              am014_substatustext="Burner pre-ignition";
              break;
            case 18:
              am014_substatustext="Burner ignition";
              break;
            case 19:
              am014_substatustext="Flame check";
              break;
            case 20:
              am014_substatustext="Fan operation at ign";
              break;
            case 30:
              am014_substatustext="Operation at setpoint";
              break;
            case 31:
              am014_substatustext="Operation reduced setpoint";
              break;
            case 32:
              am014_substatustext="Operation required setpoint";
              break;
            case 33:
              am014_substatustext="Level1 ramp";
              break;
            case 34:
              am014_substatustext="Level2 ramp";
              break;
            case 35:
              am014_substatustext="Level3 ramp";
              break;
            case 36:
              am014_substatustext="Flame protection";
              break;
            case 37:
              am014_substatustext="Stabilization time";
              break;
            case 38:
              am014_substatustext="Start min output";
              break;
            case 39:
              am014_substatustext="Heating mode interupted by DWH";
              break;
            case 41:
              am014_substatustext="Post-ventilation";
              break;
            case 44:
              am014_substatustext="Fan off";
              break;
            case 45:
              am014_substatustext="Power reduction";
              break;
            case 46:
              am014_substatustext="Automatic filling: empty";
              break;
            case 47:
              am014_substatustext="Automatic filling: low";
              break;
            case 60:
              am014_substatustext="Pump post-ventilation";
              break;
            case 95:
              am014_substatustext="Standby due water pressure";
              break;
            default:
              am014_substatustext="Unknown";
          }
          id(${device_name}_am014_substatustext).publish_state(am014_substatustext.c_str());
        }

  - can_id: 0x482
    then:
    - lambda: |-
        if(x.size() > 0) {
          uint8_t A;
          uint8_t B;

          if(x[0] == 0x01 && x[1] == 0x03) {
            
            id(${device_name}_rel_power2).publish_state(float(x[3])); //Relative Power2
          }

          if(x[0] == 0x01 && x[1] == 0x01) {
            
          //??
          }
        }
        

# GVRET component to use with SavvyCAN for remote CANbus message analysis
#canbus_gvret:
#  can:
#  - canbus_id: can1
